services:
  db:
    image: postgres:16-alpine
    container_name: clerk_be_db
    environment:
      POSTGRES_USER: clerk_user
      POSTGRES_PASSWORD: clerk_password
      POSTGRES_DB: clerk_be
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
